name: Onboard repository
description: Onboard repository onto system
title: Request to onboard repository onto system

labels:
- onboard-repository

assignees:
- danial-kurtumerov

body:
- type: markdown
  attributes:
    value: |
      For github organization `my-company` only. This Issue will be processed
      automatically. Once completed, your repository will added to the `Role`
      AWS role, and an AWS ECR repository will be created for you. This ECR
      repository will store your built container images, allowing you to use
      `company/onboarding-repo/.github/actions/ecr-build-and-push@main` in your
      CI/CD pipeline. The processing of this Issue follows these steps:
      1. Grant Read Access: You provide read access to your repository so we
      can verify it exists. This helps us avoid typos and prevents AWS from
      being cluttered with records for non-existent repositories.
      2. Fill the Template: You complete the provided Issue template.
      3. Automated Validation: We verify the data you've entered. If an error
      is detected, the github-actions bot will leave a comment explaining the
      cause. If this happens, simply edit the existing Issue to restart the
      process - there is no need to close it and open a new one.
      4. AWS Update & Completion: Once the data is confirmed as correct, we
      will update the AWS records. The github-actions bot will post a success
      comment and close the Issue as completed.
      Note: You can typically expect to see a comment from the bot within two
      minutes of creating the Issue.

- type: input
  id: repository_name
  attributes:
    label: Repository name
    description: |
      Name of the existing repository to onboard onto system. Don't use spaces
      in names. Follow naming convention: department-application or
      project-descriptive-repository-name, e. g. `ml-llm`, `frontend-chat`.
  validations:
    required: true
