name: Onboard repository
description: Onboard repository onto system
title: Request to onboard repository onto system

labels:
- onboard-repository

assignees:
- danial-kurtumerov

body:
- type: markdown
  attributes:
    value: |
      # 📦 Onboard repository
      
      Once completed, your repository will be added to the `Role` AWS role, and an AWS ECR repository will be created for you. This ECR repository will store your container images, allowing you to use [ecr-build-and-push](https://github.com/company/repository/blob/feat/onboarding_action/.github/actions/ecr-build-and-push/action.yml) action in your CI/CD pipeline. 
      
      **🔧⚙️ Processing flow:**
      1. You provide read access to your repository so we can verify it exists. This helps us avoid typos and prevents AWS from being cluttered with records for non-existent repositories.
      2. You complete the provided Issue template.
      3. We verify the data you've entered. If an error is detected, the `github-actions bot` will leave a comment explaining the cause. If this happens, simply edit the existing Issue to restart the process - there is no need to close it and open a new one.
      4. Once the data is confirmed as correct, we will update the AWS records. The github-actions bot will post a success comment and close the Issue as completed.
      
      **☝️🤓 Notes:**

      1. You can typically expect to see a comment from the `github-actions bot` within two minutes of creating the Issue.
      2. For github organization `my-company` only.
      3. This Issue will be processed automatically.

- type: input
  id: repository_name
  attributes:
    label: Repository name
    description: |
      Name of the existing repository to onboard onto system. Don't use spaces
      in names. Follow naming convention: department-application or
      project-descriptive-repository-name, e. g. `ml-llm`, `frontend-chat`.
  validations:
    required: true
