name: "onboard-repository"

on:
  issues:
    types: [opened, reopened, edited]

jobs:
  onboard-repository:
    name: "onboard-repository"
    runs-on: ['ubuntu-24.04']
    environment: onboarding-approval

    env:
      ONBOARD_REPO_EVENT: ${{ github.event_name }}
      ONBOARD_REPO_TITLE: ${{ github.event.issue.title }}
      ONBOARD_REPO_NUMBER: ${{ github.event.issue.number }}
      ONBOARD_REPO_MESSAGE: ${{ github.event.issue.body }}
      ISSUE_REPO_URL: ${{ github.event.issue.repository_url }}
      REPO_NAME: ${{ github.event.repository.full_name }}
      REPO_URL: ${{ github.event.repository.url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    if: contains(github.event.issue.labels.*.name, 'onboard-repository')

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.2"

      - name: Onboard repository
        run:
          uv run ./scripts/onboarding.py
        env:
          SNOW_USERNAME: ${{ secrets.SNOW_USERNAME }}
          SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}